[+ autogen5 template +]
/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */

#include <avr/io.h>
[+IF (=(get "UseLib") "1")+]#include <config.h>[+ENDIF+]
[+IF (=(get "configUSART0") "1" ) +]#include <usart.h>[+ENDIF+]

void init_io(void)
{
	[+IF (=(get "configUSART0") "1" ) +]usart0_init();[+ENDIF+]
}	

int main(void)
{

	while(1);
	return (0);
}
